version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '23:00'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    labels:
      - dependencies
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '23:00'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    labels:
      - dependencies
