# Stage 1: Build stage
FROM node:18.20-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

# Run any build commands (if required)
# RUN yarn build

# Stage 2: Production stage
FROM node:18.20-alpine

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3001

CMD ["sh", "-c", "yarn migration:apply && yarn dev"]